# Edit the descriptions in the "stages" section of this file.
# Apply updates at: https://app-staging.codecrafters.io/courses/writers-stg/admin/updates

slug: "writers-stg"
name: "Build your own writers stg"
short_name: "writers-stg"
release_status: "alpha"
description_md: |-
  Add a description for your course here.
short_description_md: |-
  Add a short description for your course here.
completion_percentage: 15
languages:
  - slug: "go"
  - slug: "python"
  - slug: "rust"

marketing:
  difficulty: medium
  sample_extension_idea_title: "My course extension idea"
  sample_extension_idea_description: "A description for my course extension idea"
  testimonials: []

stages:
  - slug: "init"
    name: "The first stage"
    difficulty: very_easy
    description_md: |-
      In this stage, you'll implement a TCP server that listens on port 4221.

      [TCP](https://www.cloudflare.com/en-ca/learning/ddos/glossary/tcp-ip/) is the underlying protocol used by HTTP servers.


      ### Tests

      The tester will execute your program like this:

      ```
      $ ./your_server.sh
      ```

      Then, the tester will try to connect to your server on port 4221. The connection must succeed for you to pass this stage.

    marketing_md: |-
      In this stage, we'll do XYZ.

  - slug: "second"
    name: "The second stage"
    difficulty: very_easy
    description_md: |-
      In this stage, we'll do XYZ

      **Example:** ABC

      Your program will be executed like this:

      ```bash
      $ echo "apple" | ./your_executable.sh -E "a"
      ```

      You program must ABCD.

    marketing_md: |-
      In this stage, we'll do XYZ.
