# Edit the descriptions in the "stages" section of this file.
# Apply updates at: https://app-staging.codecrafters.io/courses/writers-stg/admin/updates

slug: "writers-stg"
name: "Build your own writers stg"
short_name: "writers-stg"
release_status: "alpha"
description_md: |-
  Add a description for your course here.
short_description_md: |-
  Add a short description for your course here.
completion_percentage: 15
languages:
  - slug: "go"
  - slug: "python"
  - slug: "rust"

marketing:
  difficulty: medium
  sample_extension_idea_title: "My course extension idea"
  sample_extension_idea_description: "A description for my course extension idea"
  testimonials: []

stages:
  - slug: "oq4"
    name: "Read header"
    difficulty: very_easy
    description_md: |-
      In this stage, you'll implement the `/files/{filename}` endpoint, which returns a requested file to the client.

      ### Tests
      The tester will execute your program with a `--directory` flag. The `--directory` flag specifies the directory where the files are stored, as an absolute path.
      ```
      $ ./your_server.sh --directory /tmp/
      ```

      The tester will then send two `GET` requests to the `/files/{filename}` endpoint on your server.

      #### First request
      The first request will ask for a file that exists in the files directory:
      ```
      $ echo -n 'Hello, World!' > /tmp/foo
      $ curl -i http://localhost:4221/files/foo
      ```

      Your server must respond with a `200` response that contains the following parts:
      -   `Content-Type` header set to `application/octet-stream`.
      -   `Content-Length` header set to the size of the file, in bytes.
      -   Response body set to the file contents.
      ```
      HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: 14\r\n\r\nHello, World!
      ```

      #### Second request
      The second request will ask for a file that doesn't exist in the files directory:
      ```
      $ curl -i http://localhost:4221/files/non_existant_file
      ```

      Your server must respond with a `404` response:
      ```
      HTTP/1.1 404 Not Found\r\n\r\n
      ```
    marketing_md: |-
      In this stage, we'll do XYZ.

  - slug: "ji3"
    name: "The second stage"
    difficulty: very_easy
    description_md: |-
      In this stage, we'll do XYZ

    marketing_md: |-
      In this stage, we'll do XYZ.
