# Edit the descriptions in the "stages" section of this file.
# Apply updates at: https://app-staging.codecrafters.io/courses/writers-stg/admin/updates

slug: "writers-stg"
name: "Build your own writers stg"
short_name: "writers-stg"
release_status: "alpha"
description_md: |-
  Add a description for your course here.
short_description_md: |-
  Add a short description for your course here.
completion_percentage: 15
languages:
  - slug: "go"
  - slug: "python"
  - slug: "rust"

marketing:
  difficulty: medium
  sample_extension_idea_title: "My course extension idea"
  sample_extension_idea_description: "A description for my course extension idea"
  testimonials: []

stages:
  - slug: "oq4"
    name: "Read header"
    difficulty: very_easy
    description_md: |-
      TEST:
      - adfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdafadfoiajdsfoiadsjf adsfadsfdaf
        SECOND LINE
      - dsafdsafads
        ```
        fadsfadf
        ```
      - fdasfdsafsad
    marketing_md: |-
      In this stage, we'll do XYZ.

  - slug: "ji3"
    name: "The second stage"
    difficulty: very_easy
    description_md: |-
      In this stage, we'll do XYZ

    marketing_md: |-
      In this stage, we'll do XYZ.
