# Edit the descriptions in the "stages" section of this file.
# Apply updates at: https://app-staging.codecrafters.io/courses/writers-stg/admin/updates

slug: "writers-stg"
name: "Build your own writers stg"
short_name: "writers-stg"
release_status: "alpha"
description_md: |-
  Add a description for your course here.
short_description_md: |-
  Add a short description for your course here.
completion_percentage: 15
languages:
  - slug: "go"
  - slug: "python"
  - slug: "rust"

marketing:
  difficulty: medium
  sample_extension_idea_title: "My course extension idea"
  sample_extension_idea_description: "A description for my course extension idea"
  testimonials: []

stages:
  - slug: "oq4"
    name: "Read header"
    difficulty: very_easy
    description_md: |-
      In this stage, you'll add support for [`gzip` compression](https://www.gzip.org/) to your HTTP server.

      ### Tests

      The tester will execute your program like this:
      ```
      $ ./your_server.sh
      ```

      Then, the tester will send a `GET` request to the `/echo/{str}` endpoint on your server. The request will contain an `Accept-Encoding` header that includes `gzip`.
      ```
      $ curl -v -H "Accept-Encoding: gzip" http://localhost:4221/echo/abc | hexdump -C
      ```

      Your server's response must contain the following:
      - `200` response code.
      - `Content-Type` header set to `text/plain`.
      - `Content-Encoding` header set to `gzip`.
      - `Content-Length` header set to the size of the compressed body.
      - Response body set to the `gzip`-compressed `str` parameter.

      ```
      HTTP/1.1 200 OK
      Content-Encoding: gzip
      Content-Type: text/plain
      Content-Length: 23

      1F 8B 08 00 00 00 00 00  // Hexadecimal representation of the response body
      00 03 4B 4C 4A 06 00 C2
      41 24 35 03 00 00 00
      ```

      ### Notes

      - To check that your compressed body is correct, you can run `echo -n <uncompressed-str> | gzip | hexdump -C`.
      - It's normal for a very short string like `abc` to increase in size when compressed.
    marketing_md: |-
      In this stage, we'll do XYZ.

  - slug: "ji3"
    name: "The second stage"
    difficulty: very_easy
    description_md: |-
      In this stage, we'll do XYZ

    marketing_md: |-
      In this stage, we'll do XYZ.
